name: Terraform
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
permissions:
  id-token: write # This is required for requesting the JWT

jobs:
  terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    steps:
      - name: chekck the statefile 
        run: ls -l 
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.0 # Specify the Terraform version you need
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::982534365201:role/github_actions
          aws-region: eu-west-2

      - name: Terraform Init
        run: terraform init



      - name: Terraform Plan
        run: terraform plan
    #updated repo


      - name: Terraform Apply -auto-approbe
        env:
          TF_VAR_example: ${{ secrets.TF_VAR_EXAMPLE }}
        run: terraform plan -auto-approve
#destroying 2 times
